#未弄好

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_security?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql!@#root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 0

#config-location指定mybatis的核心文件
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  #  配置别名扫描包
  type-aliases-package: com.rfos.assistsilkworm.pojo,com.rfos.assistsilkworm.vo,com.rfos.assistsilkworm.dto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
#    日志配置-会影响性能
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#驼峰映射